version: "3"
services:
  postgres:
    image: postgres:11.13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg!password
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@cmg.com
      PGADMIN_DEFAULT_PASSWORD: pg!password
    ports:
      - "4321:80"
